export const SET_CURRENT_LOCALE = 'SET_CURRENT_LOCALE';
export const TRIGGER_AUTH_MODAL = 'TRIGGER_AUTH_MODAL';
export const SET_AUTH_DATA = 'SET_AUTH_DATA';
export const SET_WINDOW_WIDTH = 'SET_WINDOW_WIDTH';
export const SET_UNREAD_MESSAGES = 'SET_UNREAD_MESSAGES';
export const SET_LAST_OFFER_DATA = 'SET_LAST_OFFER_DATA';
