export const SET_ORDER_DETAILS_DATA = 'SET_ORDER_DETAILS_DATA';
export const SET_ORDER_DETAILS_LOADING = 'SET_ORDER_DETAILS_LOADING';
export const RESET_ORDER_DETAILS_STORE = 'RESET_ORDER_DETAILS_STORE';
