export const SET_CREATE_OFFER_STATE = 'SET_CREATE_OFFER_STATE';
export const SET_CREATE_OFFER_LOADING = 'SET_CREATE_OFFER_LOADING';
export const SET_CREATE_OFFER_PARAMS = 'SET_CREATE_OFFER_PARAMS';
export const RESET_CREATE_OFFER_STORE = 'RESET_CREATE_OFFER_STORE';
export const SET_CREATE_OFFER_PUBLISHED_DATA =
  'SET_CREATE_OFFER_PUBLISHED_DATA';
export const SET_CREATE_OFFER_CATEGORIES = 'SET_CREATE_OFFER_CATEGORIES';

export const MAX_UPLOAD_FILE_SIZE = 52428800; // 50mb