export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';

export const SAVE_NOTIFICATION = 'SAVE_NOTIFICATION';
export const SAVE_NOTIFICATION_SUCCESS = 'SAVE_NOTIFICATION_SUCCESS';
export const SAVE_NOTIFICATION_FAIL = 'SAVE_NOTIFICATION_FAIL';

export const UNSAVE_NOTIFICATION = 'UNSAVE_NOTIFICATION';
export const UNSAVE_NOTIFICATION_SUCCESS = 'UNSAVE_NOTIFICATION_SUCCESS';
export const UNSAVE_NOTIFICATION_FAIL = 'UNSAVE_NOTIFICATION_FAIL';
