export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_CATEGORY_SERVICE = 'SET_CATEGORY_SERVICE';
export const SET_CATEGORY_SERVICE_LIST = 'SET_CATEGORY_SERVICE_LIST';
export const SET_CATEGORY_SUBCATEGORIE = 'SET_CATEGORY_SUBCATEGORIE';
export const SET_CATEGORY_SUBCATEGORIES_LIST =
  'SET_CATEGORY_SUBCATEGORIES_LIST';
export const SET_CATEGORY_SUBCATEGORIES_SERVICE =
  'SET_CATEGORY_SUBCATEGORIES_SERVICE';
export const SET_CATEGORY_SUBCATEGORIES_SERVICES_LIST =
  'SET_CATEGORY_SUBCATEGORIES_SERVICES_LIST';
