export const SET_EDIT_OFFER_INITIAL_DATA = 'SET_EDIT_OFFER_INITIAL_DATA';
export const RESET_EDIT_OFFER_STORE = 'RESET_EDIT_OFFER_STORE';
export const SET_EDIT_OFFER_EDITABLE_DATA = 'SET_EDIT_OFFER_EDITABLE_DATA';
export const SET_EDIT_OFFER_PUBLISHED_DATA = 'SET_EDIT_OFFER_PUBLISHED_DATA';
