export const GET_ALL_OFFERS = 'GET_ALL_OFFERS';
export const GET_ALL_OFFERS_SUCCESS = 'GET_ALL_OFFERS_SUCCESS';
export const GET_ALL_OFFERS_FAIL = 'GET_ALL_OFFERS_FAIL';

export const CREATE_OFFER_SUCCESS = 'CREATE_OFFER_SUCCESS';
export const SET_SELF_OFFER_LIST = 'SET_SELF_OFFER_LIST';
export const SET_CURRENT_OFFER = 'SET_CURRENT_OFFER';
export const EDIT_OFFER = 'EDIT_OFFER';
export const EDIT_PARTIONAL_OFFER = 'EDIT_PARTIONAL_OFFER';
export const ACTIVATE_OFFER = 'ACTIVATE_OFFER';
export const DEACTIVATE_OFFER = 'DEACTIVATE_OFFER';
export const ARCHIVE_OFFER = 'ARCHIVE_OFFER';
export const FOLLOW_OFFER = 'FOLLOW_OFFER';
export const UNFOLLOW_OFFER = 'UNFOLLOW_OFFER';
export const GET_SELF_OFFERS = 'GET_SELF_OFFERS';
export const GET_FOLLOWING_OFFERS = 'GET_FOLLOWING_OFFERS';

export const SET_PUBLIC_PROFILE_DATA = 'SET_PUBLIC_PROFILE_DATA';
export const RESET_OFFERS = 'RESET_OFFERS';
