export const SET_CREATE_ORDER_OFFER_DATA = 'SET_CREATE_ORDER_OFFER_DATA';
export const SET_CREATE_ORDER_ORDER_DATA = 'SET_CREATE_ORDER_ORDER_DATA';
export const CREATE_ORDER_RESET_STORE = 'CREATE_ORDER_RESET_STORE';
